server:
  port: 8088

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/clinic
    username: sqladmin
    password: password

  jpa:
    properties:
      hibernate:
        jdbc:
          time_zone: UTC